spring.application.name=smartphone
# ===============================
# H2 DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:h2:mem:smartphone-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# IMPORTANT FOR data.sql
# ===============================
spring.jpa.defer-datasource-initialization=true

# JWT TOKEN
jwt.secret=TXlTZWNyZXRLZXlGb3JTbWFydHBob25lQXBwbGljYXRpb25Kd3RUb2tlbjEyMzQ1Njc4OTA=
jwt.expiration=86400000